#!/usr/bin/env python3
"""Regressions for the auditd-rules-v1 APPLY mechanism (fstec-logging-2025 приложение 2, п.4;
SRC-0053).

PURPOSE=DEFENSIVE_COMPLIANCE_VALIDATION
SCOPE=LOCAL_REPOSITORY_AND_OWN_TEST_FIXTURES
HOST_MUTATION=false

Каждый случай работает на дереве во временном каталоге внутри репозитория (`_root`:
`etc/audit/rules.d/*.rules`, `etc/audit/audit.rules`, `usr/sbin/auditctl`, `usr/sbin/augenrules`);
auditctl и augenrules заменены моделью (`_run`): загрузка склеивает rules.d/*.rules, как augenrules,
и отказывает на дубле правила. Правила ядра модель пишет в файл `kernel` корня; `usr/sbin/auditctl`
выводит его — этим же файлом пользуется CHECK. Файлы принадлежат текущему пользователю — адаптеры
при заданном корне принимают его вместо root. Карта разбиения auditd v6 (решение пользователя
01.10.2026).
"""

from __future__ import annotations

import importlib.util
import os
from pathlib import Path
import re
import shutil
import subprocess
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[2]
ADAPTER = ROOT / "product/apply-adapters/product-auditd-rules-apply-v1.py"
CHECK_ADAPTER = ROOT / "product/adapters/product-auditd-rules-check-v1.py"
CONTROLS = ROOT / "controls/fstec-core/logging-2025"
BASH = shutil.which("bash")


def load(path, name):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


A = load(ADAPTER, "slp_auditd_rules_apply")
C = load(CHECK_ADAPTER, "slp_auditd_rules_check")

# Штатный rules.d/audit.rules пакета auditd на средах 1–7 (разведка 01.10.2026).
STOCK = b"## First rule - delete all\n-D\n\n## Increase the buffers to survive stress events.\n-b 8192\n\n-f 1\n\n--backlog_wait_time 60000\n"
CONTROL_LINES = (b"-D", b"-b", b"-f", b"--backlog_wait_time", b"-e")
NORMAL = dict(A.RULES)
NORMAL.update({normal: normal for _source, normal in A.RULES})


class Host:
    """Временный корень с каталогами auditd, штатными файлами правил и моделью ядра."""

    def __init__(self, td, kernel=(), enabled=1, load_rc=0):
        self.root = Path(td)
        self.audit = self.root / "etc/audit"
        self.rules_d = self.audit / "rules.d"
        self.rules_d.mkdir(parents=True)
        os.chmod(self.audit, 0o750)
        os.chmod(self.rules_d, 0o750)
        self.write(self.rules_d / "audit.rules", STOCK)
        self.audit_rules = self.audit / "audit.rules"
        self.write(self.audit_rules, b"## This file is automatically generated from /etc/audit/rules.d\n" + STOCK)
        self.product = self.rules_d / "50-securelinux-policy.rules"
        (self.root / "usr/sbin").mkdir(parents=True)
        self.kernel_file = self.root / "kernel"
        auditctl = self.root / "usr/sbin/auditctl"
        auditctl.write_text("#!/bin/sh\ncat '%s'\n" % self.kernel_file, encoding="utf-8")
        auditctl.chmod(0o755)
        augenrules = self.root / "usr/sbin/augenrules"
        augenrules.write_text("#!/bin/sh\nexit 0\n", encoding="ascii")
        augenrules.chmod(0o755)
        self.set_kernel(list(kernel))
        self.enabled = enabled
        self.load_rc = list(load_rc) if isinstance(load_rc, (list, tuple)) else [load_rc]
        self.after_load = None
        self.calls = []

    @staticmethod
    def write(path, data, mode=0o640):
        path.write_bytes(data)
        os.chmod(path, mode)

    def set_kernel(self, lines):
        self.kernel = list(lines)
        self.kernel_file.write_bytes(b"".join(line + b"\n" for line in self.kernel) if self.kernel else b"No rules\n")

    def augenrules(self):
        names = A.rule_file_names(os.listdir(os.fsencode(self.rules_d)))
        body = b"".join((self.rules_d / os.fsdecode(n)).read_bytes() for n in names)
        self.write(self.audit_rules, b"## This file is automatically generated from /etc/audit/rules.d\n" + body)
        loaded = []
        for line in body.split(b"\n"):
            line = line.strip()
            if not line or line.startswith(b"#") or line.split()[0] in CONTROL_LINES:
                continue
            rule = NORMAL.get(line, line)
            if rule in loaded:
                self.set_kernel(loaded)
                return 1
            loaded.append(rule)
        self.set_kernel(loaded)
        return 0

    def run(self, argv, timeout):
        self.calls.append(tuple(argv))
        if argv == [A.AUDITCTL, "-l"]:
            return subprocess.CompletedProcess(argv, 0, self.kernel_file.read_bytes(), b"")
        if argv == [A.AUDITCTL, "-s"]:
            out = b"enabled %d\nfailure 1\npid 713\nbacklog_limit 8192\n" % self.enabled
            return subprocess.CompletedProcess(argv, 0, out, b"")
        if argv == [A.AUGENRULES, "--load"]:
            rc = self.augenrules()
            forced = self.load_rc.pop(0) if self.load_rc else 0
            if self.after_load is not None:
                self.after_load(self)
            return subprocess.CompletedProcess(argv, forced or rc, b"", b"")
        raise AssertionError(argv)

    def execute(self, dry_run=False, privileged=True, key="table1", expected="present"):
        return A.execute_control("FSTEC-LOGGING-2025-APPENDIX2-LINUX-4-AUDIT-RULES", key, "eq", expected, True,
                                 dry_run=dry_run, privilege_check=lambda: privileged,
                                 _root=str(self.root), _run=self.run)

    def check(self):
        block = C._shell_function_for_fixture("AUD.R", str(self.rules_d), str(self.root / "usr/sbin/auditctl"))
        cp = subprocess.run([BASH, "-c", "set -u\n" + block + "\nslp_check_AUD_R\n"], text=True,
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False)
        assert cp.returncode == 0, cp.stderr
        return cp.stdout.strip().split("\t")[2:]

    def loads(self):
        return sum(1 for call in self.calls if call == (A.AUGENRULES, "--load"))


class Contract(unittest.TestCase):
    def test_parser_matches_check_adapter(self):
        self.assertEqual(A.PARSER, C.PARSER)
        self.assertEqual(A.PARAMETER_KIND, C.PARAMETER_KIND)
        self.assertEqual((A.CANONICAL_KEY, A.CANONICAL_EXPECTED, A.RULES_DIR, A.AUDITCTL),
                         (C.CANONICAL_KEY, C.CANONICAL_EXPECTED, C.CANONICAL_LOCATOR, C.AUDITCTL))
        self.assertFalse(hasattr(A, "INSTALLS_PACKAGES"))

    def test_rule_set_is_table1_without_myapp(self):
        text = (CONTROLS / "fstec-logging-2025-appendix2-linux-4-audit-rules.yaml").read_text(encoding="utf-8")
        quote = re.search(r'^  quote: "(.*)"$', text, re.M).group(1)
        rules = re.findall(r"sudo auditctl (.+?)(?= sudo auditctl |$| Категория)", quote)
        self.assertEqual(len(rules), 26)
        self.assertEqual([r for r in rules if "myapp" in r], ["-a exit,always -F path=/usr/bin/myapp -F perm=x -k myapp_execution"])
        self.assertEqual([source.decode("ascii") for source, _normal in A.RULES], [r for r in rules if "myapp" not in r])
        self.assertIn('  kind: "auditd-rules"\n  locator: "/etc/audit/rules.d"\n  key: "table1"\n', text)
        self.assertIn('  op: "eq"\n  value: "present"\n', text)
        self.assertIn("apply:\n  supported: true\n", text)

    def test_product_bytes(self):
        lines = A.PRODUCT_BYTES.split(b"\n")
        self.assertEqual(lines[2:-1], [source for source, _normal in A.RULES])
        self.assertTrue(all(line.startswith(b"# ") for line in lines[:2]))
        self.assertFalse(A.PRODUCT.endswith(A.TMP_SUFFIX))
        self.assertFalse((A.PRODUCT + A.TMP_SUFFIX).endswith(".rules"))


class Apply(unittest.TestCase):
    def test_clean_host_is_applied_and_check_passes(self):
        with tempfile.TemporaryDirectory(dir=ROOT) as td:
            host = Host(td)
            self.assertEqual(host.check(), ["VALUE", "files=0/25 kernel=0/25", "FAIL"])
            res = host.execute()
            self.assertEqual((res["outcome"], res["policy_current"]), ("APPLIED", "files=25/25 kernel=25/25"), res)
            self.assertEqual(res["transaction_commit"], "COMMITTED")
            self.assertEqual(host.product.read_bytes(), A.PRODUCT_BYTES)
            self.assertEqual(os.stat(host.product).st_mode & 0o7777, 0o640)
            self.assertEqual(host.kernel, [normal for _source, normal in A.RULES])
            self.assertEqual(host.check(), ["VALUE", "files=25/25 kernel=25/25", "PASS"])
            self.assertEqual(host.execute()["outcome"], "ALREADY_COMPLIANT")
            self.assertEqual(host.loads(), 1)

    def test_product_file_present_but_not_loaded(self):
        with tempfile.TemporaryDirectory(dir=ROOT) as td:
            host = Host(td)
            host.write(host.product, A.PRODUCT_BYTES, 0o600)
            before = os.lstat(host.product)
            res = host.execute()
            self.assertEqual(res["outcome"], "APPLIED", res)
            self.assertNotIn("PHASE1_WRITE", res["actions_attempted"])
            self.assertEqual(A.file_tuple(os.lstat(host.product)), A.file_tuple(before))

    def test_product_file_replaced_with_mode_kept(self):
        with tempfile.TemporaryDirectory(dir=ROOT) as td:
            host = Host(td)
            host.write(host.product, b"-w /etc/hosts -p wa -k hosts\n", 0o600)
            res = host.execute()
            self.assertEqual(res["outcome"], "APPLIED", res)
            self.assertEqual(host.product.read_bytes(), A.PRODUCT_BYTES)
            self.assertEqual(os.stat(host.product).st_mode & 0o7777, 0o600)

    def test_normalized_spelling_in_files_is_compliant(self):
        with tempfile.TemporaryDirectory(dir=ROOT) as td:
            host = Host(td)
            body = b"".join(b"  " + normal + b"\t\n" for _source, normal in A.RULES)
            host.write(host.rules_d / "99-site.rules", body)
            host.augenrules()
            self.assertEqual(host.execute()["outcome"], "ALREADY_COMPLIANT")
            self.assertEqual(host.check(), ["VALUE", "files=25/25 kernel=25/25", "PASS"])

    def test_dry_run_and_privilege_do_not_write(self):
        for kwargs, outcome in (({"dry_run": True}, "DRY_RUN_WOULD_APPLY"),
                                ({"privileged": False}, "ABORTED_PRECONDITION_OTHER")):
            with self.subTest(kwargs=kwargs), tempfile.TemporaryDirectory(dir=ROOT) as td:
                host = Host(td)
                self.assertEqual(host.execute(**kwargs)["outcome"], outcome)
                self.assertFalse(host.product.exists())
                self.assertEqual(host.loads(), 0)

    def test_contract_fields_are_closed(self):
        with tempfile.TemporaryDirectory(dir=ROOT) as td:
            host = Host(td)
            for kwargs in ({"key": "myapp"}, {"expected": "absent"}):
                self.assertEqual(host.execute(**kwargs)["outcome"], "NOT_ELIGIBLE_APPLY_UNSUPPORTED")
        for args in (("C", "/etc/audit/audit.rules", "table1", "eq", "present"),
                     ("C", "/etc/audit/rules.d", "table1", "ge", "present")):
            with self.assertRaises(ValueError):
                C.shell_function(*args)


class Refusals(unittest.TestCase):
    def refused(self, prepare, outcome, reason, **host_kwargs):
        with tempfile.TemporaryDirectory(dir=ROOT) as td:
            host = Host(td, **host_kwargs)
            prepare(host)
            snapshot = {p: p.read_bytes() for p in host.audit.rglob("*") if p.is_file() and not p.is_symlink()}
            res = host.execute()
            self.assertEqual((res["outcome"], res["reason"]), (outcome, reason), res)
            self.assertFalse(res["mutation_performed"])
            self.assertEqual(host.loads(), 0)
            self.assertEqual({p: p.read_bytes() for p in snapshot}, snapshot)
            return res

    def test_missing_tools(self):
        for tool in ("auditctl", "augenrules"):
            with self.subTest(tool=tool):
                self.refused(lambda h, t=tool: (h.root / "usr/sbin" / t).unlink(),
                             "ABORTED_PRECONDITION_OTHER", "tools:missing:" + tool)

    def test_untrusted_objects(self):
        cases = (
            (lambda h: os.chmod(h.rules_d, 0o770), "auditd-rules:dir-untrusted"),
            (lambda h: h.write(h.product, b"x\n", 0o660), "auditd-rules:untrusted"),
            (lambda h: os.symlink("/dev/null", h.product), "auditd-rules:untrusted"),
            (lambda h: os.link(h.audit_rules, h.root / "hard"), "auditd-rules:untrusted"),
            (lambda h: os.symlink("/dev/null", h.rules_d / "60-x.rules"), "auditd-rules:other-untrusted"),
            (lambda h: h.write(h.rules_d / "60-x.rules", b"-w /etc/hosts -k h\n", 0o666), "auditd-rules:other-untrusted"),
        )
        for prepare, reason in cases:
            with self.subTest(reason=reason):
                res = self.refused(prepare, "ABORTED_PRECONDITION_CONFLICT", reason)
                self.assertEqual(res["operator_decision"]["class"], "ADMIN_ACTION_REQUIRED")

    def test_rule_in_other_file_is_conflict(self):
        for line in (A.RULES[3][0], A.RULES[23][1]):
            with self.subTest(line=line):
                self.refused(lambda h, x=line: h.write(h.rules_d / "60-site.rules", x + b"\n"),
                             "ABORTED_PRECONDITION_CONFLICT", "auditd-rules:rule-in-other-file")

    def test_locked_rules(self):
        self.refused(lambda h: h.write(h.rules_d / "99-finalize.rules", b"-e 2\n"),
                     "ABORTED_PRECONDITION_CONFLICT", "auditd-rules:locked")
        self.refused(lambda h: None, "ABORTED_PRECONDITION_CONFLICT", "auditd-rules:locked", enabled=2)
        # Закомментированная строка и `-e 1` не блокируют.
        with tempfile.TemporaryDirectory(dir=ROOT) as td:
            host = Host(td)
            host.write(host.rules_d / "99-finalize.rules", b"# -e 2\n-e 1\n")
            self.assertEqual(host.execute()["outcome"], "APPLIED")

    def test_invalid_bytes_and_hidden_or_foreign_names(self):
        self.refused(lambda h: h.write(h.rules_d / "60-x.rules", b"\x00\n"),
                     "ABORTED_PRECONDITION_OTHER", "auditd-rules:invalid-bytes")
        with tempfile.TemporaryDirectory(dir=ROOT) as td:
            host = Host(td)
            # Не загружаются augenrules: скрытый файл и имя без окончания .rules.
            host.write(host.rules_d / ".60-x.rules", A.RULES[0][0] + b"\n", 0o666)
            host.write(host.rules_d / "60-x.rules.bak", A.RULES[0][0] + b"\n", 0o666)
            self.assertEqual(host.execute()["outcome"], "APPLIED")

    def test_kernel_list_failure(self):
        with tempfile.TemporaryDirectory(dir=ROOT) as td:
            host = Host(td)
            real = host.run

            def run(argv, timeout):
                if argv == [A.AUDITCTL, "-l"]:
                    return subprocess.CompletedProcess(argv, 1, b"", b"")
                return real(argv, timeout)

            host.run = run
            res = host.execute()
            self.assertEqual((res["outcome"], res["reason"]), ("ABORTED_PRECONDITION_OTHER", "auditctl:list-failed"))


class Compensation(unittest.TestCase):
    def assert_restored(self, host, res, before, kernel, reason, outcome="FAILED_NOT_COMMITTED"):
        self.assertEqual((res["outcome"], res["reason"]), (outcome, reason), res)
        self.assertTrue(res["mutation_performed"])
        self.assertEqual(res["transaction_commit"], "NOT_COMMITTED")
        if outcome == "FAILED_NOT_COMMITTED":
            self.assertFalse(host.product.exists())
            self.assertEqual(host.audit_rules.read_bytes(), before)
            self.assertEqual(host.kernel_file.read_bytes(), kernel)

    def test_load_failure_is_rolled_back(self):
        with tempfile.TemporaryDirectory(dir=ROOT) as td:
            host = Host(td, load_rc=[1, 0])
            before, kernel = host.audit_rules.read_bytes(), host.kernel_file.read_bytes()
            res = host.execute()
            self.assert_restored(host, res, before, kernel, "augenrules:load-failed")
            self.assertEqual(host.loads(), 2)

    def test_postcheck_failure_is_rolled_back(self):
        with tempfile.TemporaryDirectory(dir=ROOT) as td:
            host = Host(td)
            before, kernel = host.audit_rules.read_bytes(), host.kernel_file.read_bytes()

            def drop_one(h):
                if h.product.exists():
                    h.set_kernel(h.kernel[:-1])
                    h.after_load = None

            host.after_load = drop_one
            res = host.execute()
            self.assert_restored(host, res, before, kernel, "auditd-rules:postcheck-failed")

    def test_audit_rules_bytes_restored_after_load(self):
        with tempfile.TemporaryDirectory(dir=ROOT) as td:
            # audit.rules F1 не совпадает со склейкой rules.d: откат возвращает именно байты F1.
            host = Host(td, load_rc=[1, 0])
            host.write(host.audit_rules, b"## stale\n-D\n", 0o600)
            res = host.execute()
            self.assert_restored(host, res, b"## stale\n-D\n", b"No rules\n", "augenrules:load-failed")
            self.assertEqual(os.stat(host.audit_rules).st_mode & 0o7777, 0o600)

    def test_failed_rollback_is_compensation_failure(self):
        with tempfile.TemporaryDirectory(dir=ROOT) as td:
            host = Host(td, kernel=[b"-w /etc/hosts -p wa -k hosts"], load_rc=[1, 0])
            before = host.audit_rules.read_bytes()
            # Правило загружено вручную, в файлах его нет: augenrules при откате его не вернёт.
            res = host.execute()
            self.assert_restored(host, res, before, None, "augenrules:load-failed", outcome="FAILED_COMPENSATION")
            self.assertFalse(host.product.exists())

    def test_change_before_load_restores_product_without_load(self):
        with tempfile.TemporaryDirectory(dir=ROOT) as td:
            host = Host(td)
            real = A._write

            def write(root, path, data, refs, dirs, owner, mode, full=True):
                st = real(root, path, data, refs, dirs, owner, mode, full)
                if path == A.PRODUCT:
                    host.write(host.rules_d / "70-late.rules", b"-w /etc/hosts -k h\n")
                return st

            A._write = write
            try:
                res = host.execute()
            finally:
                A._write = real
            self.assertEqual((res["outcome"], res["reason"]),
                             ("FAILED_NOT_COMMITTED", "auditd-rules:changed-before-load"), res)
            self.assertEqual(host.loads(), 0)
            self.assertFalse(host.product.exists())

    def test_write_protocol_refuses_changed_object(self):
        with tempfile.TemporaryDirectory(dir=ROOT) as td:
            host = Host(td)
            dirs, files, others = A.observe(str(host.root))
            refs = {A.PRODUCT: None, A.AUDIT_RULES: A._tuple(files[A.AUDIT_RULES][0])}
            host.write(host.product, b"x\n", 0o600)
            with self.assertRaises(A._Changed):
                A._write(str(host.root), A.PRODUCT, A.PRODUCT_BYTES, refs, dirs, (os.geteuid(), os.getegid()), 0o640)
            host.product.unlink()
            # Новый файл правил в rules.d — тоже расхождение с F1.
            host.write(host.rules_d / "70-late.rules", b"-w /etc/hosts -k h\n")
            with self.assertRaises(A._Changed):
                A._write(str(host.root), A.PRODUCT, A.PRODUCT_BYTES, refs, dirs, (os.geteuid(), os.getegid()), 0o640)
            self.assertFalse(host.product.exists())
            self.assertFalse(Path(str(host.product) + A.TMP_SUFFIX).exists())


class Regressions(unittest.TestCase):
    """Регрессии: подмена каталога rules.d, файл продукта после загрузки отката, жёсткая ссылка
    у неизменяемого файла правил."""

    def test_b01_replaced_rules_dir_is_not_touched(self):
        with tempfile.TemporaryDirectory(dir=ROOT) as td:
            host = Host(td, load_rc=[1, 0])
            moved = host.audit / "rules.d.old"

            def swap(h):
                if moved.exists():
                    return
                os.rename(h.rules_d, moved)
                h.rules_d.mkdir()
                os.chmod(h.rules_d, 0o750)
                h.write(h.product, b"foreign\n")

            host.after_load = swap
            res = host.execute()
            self.assertEqual((res["outcome"], res["reason"]), ("FAILED_COMPENSATION", "augenrules:load-failed"), res)
            self.assertEqual(host.product.read_bytes(), b"foreign\n")
            self.assertEqual((moved / "50-securelinux-policy.rules").read_bytes(), A.PRODUCT_BYTES)

    def test_b02_product_reappearing_during_rollback_load(self):
        with tempfile.TemporaryDirectory(dir=ROOT) as td:
            host = Host(td, load_rc=[1, 0])
            loads = []

            def reappear(h):
                loads.append(1)
                if len(loads) == 2:
                    h.write(h.product, A.PRODUCT_BYTES)

            host.after_load = reappear
            res = host.execute()
            self.assertEqual((res["outcome"], res["reason"]), ("FAILED_COMPENSATION", "augenrules:load-failed"), res)
            self.assertTrue(host.product.exists())

    def test_b03_hard_link_of_read_only_rules_file_is_accepted(self):
        with tempfile.TemporaryDirectory(dir=ROOT) as td:
            host = Host(td)
            os.link(host.rules_d / "audit.rules", host.root / "audit.rules.link")
            res = host.execute()
            self.assertEqual(res["outcome"], "APPLIED", res)

    def test_unlink_checked_refuses_non_regular_and_swapped_dir(self):
        with tempfile.TemporaryDirectory(dir=ROOT) as td:
            host = Host(td)
            dirs, _files, _others = A.observe(str(host.root))
            host.product.mkdir()
            self.assertFalse(A._unlink_checked(str(host.root), A.PRODUCT, dirs))
            self.assertTrue(host.product.is_dir())
            host.product.rmdir()
            self.assertTrue(A._unlink_checked(str(host.root), A.PRODUCT, dirs))


class CheckObserver(unittest.TestCase):
    """CHECK SRC-0053 на том же корне: отсутствие — FAIL, недоверенные объекты и сбой auditctl — ERROR."""

    def test_absent_objects_fail(self):
        with tempfile.TemporaryDirectory(dir=ROOT) as td:
            host = Host(td)
            (host.root / "usr/sbin/auditctl").unlink()
            self.assertEqual(host.check(), ["VALUE", "<auditctl-absent>", "FAIL"])
            shutil.rmtree(host.rules_d)
            self.assertEqual(host.check(), ["VALUE", "<rules-dir-absent>", "FAIL"])

    def test_errors_are_explicit(self):
        cases = (
            (lambda h: os.chmod(h.rules_d, 0o770), "auditd-rules:dir-untrusted"),
            (lambda h: os.symlink("/dev/null", h.rules_d / "60-x.rules"), "auditd-rules:invalid-type"),
            (lambda h: h.write(h.rules_d / "60-x.rules", b"-e 1\n", 0o660), "auditd-rules:untrusted"),
            (lambda h: h.write(h.rules_d / "60-x.rules", b"\x00\n"), "auditd-rules:invalid-bytes"),
            (lambda h: (h.root / "usr/sbin/auditctl").write_text("#!/bin/sh\nexit 1\n", encoding="ascii"),
             "auditd-rules:auditctl-failed"),
        )
        for prepare, reason in cases:
            with self.subTest(reason=reason), tempfile.TemporaryDirectory(dir=ROOT) as td:
                host = Host(td)
                prepare(host)
                self.assertEqual(host.check(), ["ERROR", reason, "ERROR"])

    def test_partial_sets_fail(self):
        with tempfile.TemporaryDirectory(dir=ROOT) as td:
            host = Host(td)
            host.write(host.rules_d / "60-x.rules", b"".join(s + b"\n" for s, _n in A.RULES[:10]))
            self.assertEqual(host.check(), ["VALUE", "files=10/25 kernel=0/25", "FAIL"])
            host.augenrules()
            self.assertEqual(host.check(), ["VALUE", "files=10/25 kernel=10/25", "FAIL"])

    def test_rendered_function_is_read_only(self):
        src = C.shell_function("C", C.CANONICAL_LOCATOR, C.CANONICAL_KEY, "eq", C.CANONICAL_EXPECTED)
        for token in C.MUTATING_TOKENS:
            self.assertNotIn(token, src)


class Report(unittest.TestCase):
    def test_report_fields(self):
        with tempfile.TemporaryDirectory(dir=ROOT) as td:
            host = Host(td)
            rep = A.control_result_to_report(host.execute(), "s", "f")
            self.assertEqual((rep["step_rc"], rep["mechanism_id"], rep["target"]),
                             ("0", "auditd-rules-v1", "/etc/audit/rules.d/50-securelinux-policy.rules"))
            self.assertEqual(A.outcome_rc_contribution("FAILED_COMPENSATION"), "nonzero")


if __name__ == "__main__":
    unittest.main(verbosity=2)
